### ISSUE TITLE
Can't work on Grave 1.0.4

### ISSUE THREAD

**Issue by joomlacorner** [getgrav/grav-theme-hpstr#10]
Theme hpstr  don't work with Grave v.1.0.4 please check

**Comment by rhukster** [comment]
Works fine.  Just downloaded the skeleton package: https://github.com/getgrav/grav-skeleton-hpstr-site/releases/download/1.0.2/grav-skeleton-hpstr-site-v1.0.2.zip

unzipped, and pointed browser at it.. Works as expected.

I suspect you are thinking that Hpstr theme works with any content.  It supports specific pages that may not be what your content is using.  Always best to start with the skeleton with content that has been designed for it.
