### ISSUE TITLE
no admin-panel-skeleton

### ISSUE THREAD

**Issue by zeroby0** [getgrav/grav-theme-hpstr#15]
Skeleton comes with some plugins installed.
Please provide two variants of the skeleton, one with admin panel and other without it,
just like grav comes with two variants. It would be helpful to get started right away and for beginners.

**Comment by zeroby0** [comment]
Hi! I created a skeleton, but I'm not sure if it is latest or if it's bug-less
Basic skeleton is taken from skeleton in grav themes page, and added files in that to grav-admin package.

changed user/config/site.yml and user/config/system.yml file parameters.

You can find the archive [here](https://github.com/zeroby0/grav-theme-hpstr/tree/skeleton-archive)

**Comment by flaviocopes** [comment]
Hi, currently no skeleton comes with the Admin panel preinstalled. It's a decision coming from when Grav didn't have an admin panel, but I _think_ it's going to change for all skeletons, at least this is what I heard :)

**Comment by zeroby0** [comment]
oh, okay  @flaviocopes :),
There is a [fork](https://github.com/zeroby0/grav-theme-hpstr/tree/hpstr-admin) of this repository with admin panel installed in my account, anyone can use it when needed, I will try to keep it upto date with this repository.
