### ISSUE TITLE
Grav commenting plugin vs Disqus

### ISSUE THREAD

**Issue by Terchestor** [getgrav/grav-theme-hpstr#18]
Hi Andy,
First, congrats for your port that I'll like to use.
I would prefer to use the Grav commenting plugin instead of Disqus.
What am I suppose to do to configure it?
Thanks,
Alex

**Comment by flaviocopes** [comment]
@Terchestor check out the user guide which explains how to add comments to the theme: https://github.com/getgrav/grav-plugin-comments#usage

You need to put that code in here: https://github.com/getgrav/grav-theme-hpstr/blob/develop/templates/post.html.twig#L64-L67

I suggest creating a child theme to do the edits (https://learn.getgrav.org/themes/customization#theme-inheritance) to avoid having issues when an update is released.

**Comment by Terchestor** [comment]
Hi Flavio,

Thanks a lot for your help. Grav with commenting is so great!

Alex
