### ISSUE TITLE
navigation not working

### ISSUE THREAD

**Issue by malinator** [getgrav/grav-theme-hpstr#3]
Hello, I've just 'install' hpstr grav skeleton, it's very nice...unfortunately when I click on upper-left button (navigation), nothing rolls out (nothing happen). I don't change configuration expect site.yaml to fit my needs.
If this helps , you can try it on my test url - https://malinator.net/grav

Thanks

**Comment by rhukster** [comment]
I'll take a look.. I think its just not loading jquery with the new approach

**Comment by rhukster** [comment]
Should be fixed in version 1.0.3 of the theme.  You can download it directly from github here or wait an hour or so till it shows up in GPM.

**Comment by malinator** [comment]
Thanks for super fast commit :+1: It is now fixed and it is available via GPM...many thanks!
