### ISSUE TITLE
Menu doesn't disappear when clicking elsewhere

### ISSUE THREAD

**Issue by MatthiasKauer** [getgrav/grav-theme-hpstr#4]
Hi,
I'd like to use this theme for a blog and I'm clicking around the demo for evaluation. I notice that on http://demo.getgrav.org/hpstr-skeleton/ after clicking the menu, I have to select an option which then reloads the page to make the menu disappear. 
On the jekyll version here https://mmistakes.github.io/hpstr-jekyll-theme/ the menu disappears after clicking in a random area of the site. I find this behavior more intuitive and desirable.

Kind regards,
Matthias

**Comment by rhukster** [comment]
Yup, looks like a bug. I'll look into it.  Cheers.

**Comment by rhukster** [comment]
This is now available in version 1.1.0

**Comment by MatthiasKauer** [comment]
awesome! thanks for looking into this
