### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by malinator** [getgrav/grav-theme-hpstr#6]
Hello, this is not an issue, however I am not able to achieve to display only summary of post instead of full content on main page (blog).
I've tried to specify summary in post as it is described in documentation http://learn.getgrav.org/content/headers#summary but it does not help me...can you please help me with this? Thank you very much!

**Comment by malinator** [comment]
Nevermind, I've changed post.content to post.summary in page.html.twig and bingo! Thanks anyway :)

**Comment by k1ngf15h3r** [comment]
tried the solution and changed to post.summary but when done this I get no continue link
