### ISSUE TITLE
Syntax highlighting: indented block of code renders single line

### ISSUE THREAD

**Issue by mplx** [getgrav/grav-theme-hpstr#9]
Multiline code blocks which are indented - i.e. in a list - render in a single line instead of multiline while multiline blocks with no indentation render correctly as multiline.

Given markup:

1. step one

  some explanation text...
  
  ```bash
  cp a.txt b.txt
  mv b.txt c.txt
  rm c.txt
  ```

Expected indented output:
```
cp a.txt b.txt
mv b.txt c.txt
rm c.txt
```

Indented output with hpstr theme:
`cp a.txt b.txt mv b.txt c.txt rm c.txt`

**Comment by mplx** [comment]
@flaviocopes thank you very much for fixing this issue. can you tag a new release so the fixed version can be installed via gpm?

**Comment by hexplor** [comment]
done, gpm should be updated shortly

**Comment by flaviocopes** [comment]
Thanks Karol :)
